//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorVOTOCMC1.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class mc1_CustomerGCCExt
    {
        public string cIDCustomer { get; set; }
        public string cIDCustomerParent { get; set; }
        public string xCodeStatusSync { get; set; }
        public Nullable<System.DateTime> dStatusSync { get; set; }
        public string xTypeSync { get; set; }
        public string cGroupAccount { get; set; }
        public string cDocument { get; set; }
        public string cStateRegistration { get; set; }
        public string cCustomerName { get; set; }
        public string cCustomerFantasyName { get; set; }
        public string cEmailNfe { get; set; }
        public string cPhone { get; set; }
        public string cMobile { get; set; }
        public string cGroupCustomer { get; set; }
        public string cCodeTrilha { get; set; }
        public string cGroupSegmento { get; set; }
        public string cSegmento { get; set; }
        public string cGroupCentralizing { get; set; }
        public string cStreet { get; set; }
        public string cNumber { get; set; }
        public string cNeighborhood { get; set; }
        public string cComplement { get; set; }
        public Nullable<int> lZipCode { get; set; }
        public string cState { get; set; }
        public string cCity { get; set; }
        public Nullable<int> lDischargingSmoke { get; set; }
        public Nullable<int> iDischargingCustomer { get; set; }
        public Nullable<int> iPaletizado { get; set; }
        public Nullable<System.DateTime> dBirth { get; set; }
        public string cFunctionPartner { get; set; }
        public string cCustomerSAP { get; set; }
        public string cUser { get; set; }
        public string cSuframa { get; set; }
        public string cRegistrationCity { get; set; }
        public string cFile { get; set; }
        public string cReturnMessage { get; set; }
        public string xTypeReceiving { get; set; }
        public string cContacteName { get; set; }
        public string cLastNameContact { get; set; }
        public string cOffice { get; set; }
        public string cContactEmail { get; set; }
        public string cDepartment { get; set; }
        public Nullable<System.DateTime> dLastUpdate { get; set; }
        public Nullable<System.DateTime> dReturnSync { get; set; }
        public Nullable<int> mc1Enabled { get; set; }
        public Nullable<System.DateTime> mc1LastUpdate { get; set; }
        public string cContactPhone { get; set; }
        public string cContactMobile { get; set; }
        public string cIdCustomerProspect { get; set; }
        public Nullable<System.DateTime> dRelationshipSync { get; set; }
        public Nullable<decimal> nValueCreditLimitVC { get; set; }
        public Nullable<decimal> nCreditLimitVC { get; set; }
        public string cIDCompany { get; set; }
        public Nullable<int> cUserSales { get; set; }
        public string cIdUserSubstitute { get; set; }
        public Nullable<System.DateTime> dMigrationSap { get; set; }
        public byte[] mc1RowVersion { get; set; }
    }
}
